### ISSUE TITLE
Error whenever I try to insert an '{' or '#' character

### ISSUE THREAD

**Issue by alexispurslane** [BrettWitty/TADS-3-Mode-for-Emacs#4]
The error is that `last-command-char` is nil. Can be avoided if you put a random non-whitespace character first and then insert the brace or hash. I'll will investigate and fix this hopefully the day after tomorrow (spent the previous few days improving the Inform 7 emacs plugin and I need a break now). This is more a reminder to myself unless you want to help.

**Comment by BrettWitty** [comment]
I'll have a brief look. I assume it's due to one of the TADS electric commands.

**Comment by alexispurslane** [comment]
I actually figured this one out. The variable its looking for was renamed in Emacs v24 and up. I just went in and renamed it and things work fine now
